version: '2'
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:${DEBEZIUM_VERSION}
    container_name: zookeeper
    networks:
      - host
    volumes:
      - /datadrive/docker-volume/zookeeper-data:/zookeeper/data
      - /datadrive/docker-volume/zookeeper-txns:/zookeeper/txns      
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    container_name: kafka
    volumes:
      - /datadrive/docker-volume/kafka-topic:/kafka/data
    ports:
     - 9092:9092
    networks:
      - host
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  mysql:
    image: quay.io/debezium/example-mysql:${DEBEZIUM_VERSION}
    container_name: mysql
    volumes:
      - /datadrive/docker-volume/mysqldbz:/var/lib/mysql
    ports:
     - 3306:3306
    networks:
      - host
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    container_name: es01
    ports:
     - "9200:9200"
    networks:
      - host
    volumes:
      - /datadrive/docker-volume/elasticdbz01:/usr/share/elasticsearch/data
    environment:
     - http.host=0.0.0.0
     - transport.host=127.0.0.1
     - xpack.security.enabled=false
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  connect:
    image: debezium/connect-jdbc-es:${DEBEZIUM_VERSION}
    container_name: connect
    build:
      context: debezium-jdbc-es
      args:
        DEBEZIUM_VERSION: ${DEBEZIUM_VERSION}
    ports:
     - 8083:8083
     - 5005:5005
    networks:
      - host
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_source_connect_statuses
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
    container_name: kibana
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
    ports:
      - 0.0.0.0:5601:5601
    networks:
      - host
    depends_on:
      - elastic

networks:
  host:
    driver: bridge  